name: Build, Push Docker Images to ECR, and Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  build-push-and-deploy:
    name: Build, Push Docker Images to ECR, and Deploy to ECS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1"
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
      SERVICES: "service1 service2 service3"  # Update with your actual service names
      ECS_CLUSTER_NAME: "upload_ECS"
      ECS_ROLE_ARN: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/your-ecs-role"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dos2unix
        run: sudo apt-get install dos2unix

      - name: Convert line endings
        run: dos2unix ./build/git_update.sh

      - name: List build directory contents
        run: ls -alh build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          chmod +x ./build/git_update.sh
          bash ./build/git_update.sh -v major

      - name: Build, Tag, and Push the Image to Amazon ECR
        env:
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          for SERVICE in ${{ env.SERVICES }}; do
            DOCKERFILE="Dockerfile.$SERVICE"
            IMAGE_URI="${{ env.ECR_REGISTRY }}/$SERVICE:latest"
            docker build -t $IMAGE_URI -f $DOCKERFILE .
            docker push $IMAGE_URI
          done

      - name: Get image digests
        id: get-digests
        run: |
          for SERVICE in ${{ env.SERVICES }}; do
            IMAGE_URI="${{ env.ECR_REGISTRY }}/$SERVICE:latest"
            DIGEST=$(docker images --digests --format "{{.Digest}}" $IMAGE_URI)
            echo "${SERVICE}_digest=${DIGEST}" >> $GITHUB_ENV
          done

      - name: Create and push Docker manifests
        run: |
          for SERVICE in ${{ env.SERVICES }}; do
            IMAGE_URI="${{ env.ECR_REGISTRY }}/$SERVICE:latest"
            DIGEST=$(printenv ${SERVICE}_digest)
            docker manifest create $IMAGE_URI --amend $IMAGE_URI@$DIGEST
            docker manifest push $IMAGE_URI
          done

      - name: Update ECS services
        run: |
          for SERVICE in ${{ env.SERVICES }}; do
            IMAGE_URI="${{ env.ECR_REGISTRY }}/$SERVICE:latest"
            echo "Updating service $SERVICE with image $IMAGE_URI"
            aws ecs update-service --cluster ${{ env.ECS_CLUSTER_NAME }} --service $SERVICE --force-new-deployment --region $AWS_REGION
          done
