name: Build and Push Multiple Docker Images to AWS ECR

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all tags are fetched

      - name: Install dos2unix
        run: sudo apt-get install -y dos2unix

      - name: Convert line endings
        run: dos2unix ./build/git_update.sh

      - name: List build directory contents
        run: ls -alh build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          chmod +x ./build/git_update.sh
          ./build/git_update.sh -v major

      - name: Build, Tag, and Push Images to Amazon ECR
        id: build-and-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: demo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Find all Dockerfiles in the repository
          DOCKERFILES=$(find . -name 'Dockerfile*')
          
          # Loop through the Dockerfiles and build/push images
          for DOCKERFILE in $DOCKERFILES; do
            # Extract the name part for tagging
            BASENAME=$(basename $DOCKERFILE)
            TAG=${BASENAME//Dockerfile_/}
            TAG=${TAG:-default}  # Fallback to 'default' if no specific tag
            
            IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$TAG-$IMAGE_TAG"
            
            echo "Building and pushing Docker image for $DOCKERFILE to $IMAGE_URI"
            
            docker build -f $DOCKERFILE -t $IMAGE_URI .
            docker push $IMAGE_URI
            
            echo "IMAGE $IMAGE_URI is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          done

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version
          
      - name: Create ECS Cluster
        run: |
          aws ecs create-cluster --cluster-name my-cluster --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Register ECS Task Definition
        id: register-task-def
        run: |
          CLUSTER_NAME=my-cluster
          TASK_DEFINITION_NAME=my-task

          DOCKERFILES=$(find ./web_dockerfiles -name 'Dockerfile*')
          CONTAINERS_JSON=""

          for DOCKERFILE in $DOCKERFILES; do
            BASENAME=$(basename $DOCKERFILE)
            TAG=${BASENAME//Dockerfile_/}
            TAG=${TAG:-default}  # Fallback to 'default' if no specific tag
            IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$TAG-$IMAGE_TAG"

            CONTAINER_NAME="${TAG}-container"

            CONTAINERS_JSON+="{
              \"name\": \"$CONTAINER_NAME\",
              \"image\": \"$IMAGE_URI\",
              \"essential\": true,
              \"memory\": 512,
              \"cpu\": 256,
              \"portMappings\": [
                {
                  \"containerPort\": 80,
                  \"hostPort\": 80
                }
              ]
            },"
          done

          # Remove the trailing comma
          CONTAINERS_JSON=${CONTAINERS_JSON%,}

          TASK_DEF_JSON="{
            \"family\": \"$TASK_DEFINITION_NAME\",
            \"networkMode\": \"awsvpc\",
            \"containerDefinitions\": [
              $CONTAINERS_JSON
            ],
            \"requiresCompatibilities\": [\"FARGATE\"],
            \"cpu\": \"1024\",
            \"memory\": \"2048\",
            \"executionRoleArn\": \"arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_EXECUTION_ROLE\",
            \"taskRoleArn\": \"arn:aws:iam::YOUR_ACCOUNT_ID:role/YOUR_TASK_ROLE\"
          }"

          echo "$TASK_DEF_JSON" > task-def.json
          aws ecs register-task-definition --cli-input-json file://task-def.json



# name: Build, Push Docker image to ECR, and Update ECS

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build-and-deploy:
#     name: Build, Push Docker image to ECR, and Update ECS
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Log in to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2

#       - name: Build and push Docker image for Service
#         id: build-and-push-service
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: testvj
#           IMAGE_TAG: 77
#         run: |
#           echo "Building Docker image for Service..."
#           docker build -f Dockerfile_web_1 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#           echo "Pushing Docker image for Service ..."
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

#       - name: Update ECS service for Service
#         if: success()
#         env:
#           AWS_REGION: us-east-1
#           AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
#           ECR_REPOSITORY: testvj
#           IMAGE_TAG: 77
#           ECS_CLUSTER_NAME: upload_ECS
#           ECS_SERVICE_NAME: web-service
#         run: |
#           echo "Updating ECS service for Service 101 with image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
#           aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment --region $AWS_REGION

