name: Membership Tag Workflow

on:
  push:
    tags:
      - 'membership*'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List build directory contents
        run: ls -alh

      - name: Run Tests with Membership Tag
        run: |
          robot --include membership Web/RR/TestCases/
